In [1]:
import numpy as np
# Define Sigmoid Function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

# Define Derivative of Sigmoid Function
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

np.random.seed(1)

X = [[0, 0], [0, 1], [1, 0], [1, 1]]
Y = [0, 1, 1, 1]

lr = 0.5

size = [2, 3, 3, 3, 1]

weights = []
for i in range(len(size)-1):
    weights += [np.squeeze(np.random.uniform(low=0, high=1, size=(size[i], size[i+1])))]

biases = []
for i in range(1, len(size)):
    biases += [np.squeeze(np.ones((1, size[i])))]

# Store Deltas
all_delta_w = [w*0 for w in weights]
all_delta_b = [b*0 for b in biases]

for i in range(100000):
    # Forward Pass
    for x, y in zip(X, Y):
        C = 0
        z = 0
        a = [x]
        z_inp = np.array(x)
        z = []
        for w, b in zip(weights, biases):
            z += [np.dot(z_inp, w) + b]
            a += [sigmoid(z[-1])]
            z_inp = a[-1]

        # Update the Cost function
        C += 0.5*(y - a[-1])**2

        #backprop
        # layer l-1 (final layer)
        delta = (a[-1] - y) * sigmoid_der(z[-1])
        print(a[-1])
        all_delta_w[-1] += np.dot(delta, np.transpose(a[-2]))
        all_delta_b[-1] += delta

        delta_prev = delta
        for l in range(2,len(size)):
            delta = np.dot(weights[-l+1], delta_prev) * sigmoid_der(z[-l])
            print(weights[-l+1])
            all_delta_w[-l] += np.squeeze(np.transpose(np.outer(delta, np.transpose(a[-l-1]))))
            all_delta_b[-l] += delta

            delta_prev = delta

    if np.mod(i, 1000) == 0:
        print('Epoch: %d - %f\r' % (i, C/4), end='')

    # Update Weights and Biases
    weights = weights - lr/4 * all_delta_w
    biases = biases - lr/4 * all_delta_b

    all_delta_w *= 0
    all_delta_b *= 0

0.9345699871001929
[0.87638915 0.89460666 0.08504421]
[[0.67046751 0.4173048  0.55868983]
 [0.14038694 0.19810149 0.80074457]
 [0.96826158 0.31342418 0.69232262]]
[[0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]
 [0.20445225 0.87811744 0.02738759]]
0.9346276133514986
[0.87638915 0.89460666 0.08504421]
[[0.67046751 0.4173048  0.55868983]
 [0.14038694 0.19810149 0.80074457]
 [0.96826158 0.31342418 0.69232262]]
[[0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]
 [0.20445225 0.87811744 0.02738759]]
0.9347103761741546
[0.87638915 0.89460666 0.08504421]
[[0.67046751 0.4173048  0.55868983]
 [0.14038694 0.19810149 0.80074457]
 [0.96826158 0.31342418 0.69232262]]
[[0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]
 [0.20445225 0.87811744 0.02738759]]
0.9347499335580547
[0.87638915 0.89460666 0.08504421]
[[0.67046751 0.4173048  0.55868983]
 [0.14038694 0.19810149 0.80074457]
 [0.96826158 0.31342418 0.69232262]]
[[0.18626021 0.345560

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
np.dot([0.87638915, 0.89460666, 0.08504421], 0.9345699871001929)

In [ ]:
x = [1, 0]

a = [x]
z_inp = np.array(x)
z = []
for w, b in zip(weights, biases):
    z += [np.dot(z_inp, w) + b]
    a += [sigmoid(z[-1])]
    z_inp = a[-1]

print(a[-1])

# Trying out on the MNIST dataset

In [ ]:
from tensorflow.keras.datasets import mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

In [ ]:
print(np.shape(X_train))

X_train_R = np.reshape(X_train, (60000, 28*28))
X_test_R = np.reshape(X_test, (len(X_test), 28*28))

print(np.amax(X_train_R[0]))
print(np.shape(X_train_R))
print(np.shape(Y_train))

n_classes = 10

targets = np.array(Y_train).reshape(-1)
Y_train_E = np.eye(n_classes)[targets]

In [ ]:
lr = 0.5

X = X_train_R/255
Y = Y_train_E

size = [784, 100, 50, 10]

weights = []
for i in range(len(size)-1):
    weights += [np.squeeze(np.random.uniform(low=0, high=0.01, size=(size[i], size[i+1])))]

biases = []
for i in range(1, len(size)):
    biases += [np.squeeze(np.ones((1, size[i])))]

print(weights[0].shape)

# Store Deltas
all_delta_w = np.array(weights)*0
all_delta_b = np.array(biases)*0

for i in range(50000):
    # Forward Pass
    idx = np.random.choice(np.arange(len(X)), size=20, replace=False)
    X_subset = X[idx]
    Y_subset = Y[idx]
    for x, y in zip(X_subset, Y_subset):
        C = 0
        z = 0
        a = [x]
        z_inp = np.array(x)
        z = []
        for w, b in zip(weights, biases):
            z += [np.dot(z_inp, w) + b]
            a += [sigmoid(z[-1])]
            z_inp = a[-1]

        # Update the Cost function
        C += 0.5*np.sum((y - a[-1])**2)

        #backprop
        # layer l-1 (final layer)
        delta = (a[-1] - y) * sigmoid_der(z[-1])
        all_delta_w[-1] += np.squeeze(np.transpose(np.outer(delta, np.transpose(a[-2]))))
        all_delta_b[-1] += delta

        delta_prev = delta
        for l in range(2,len(size)):
            delta = np.dot(weights[-l+1], delta_prev) * sigmoid_der(z[-l])
            all_delta_w[-l] += np.squeeze(np.transpose(np.outer(delta, np.transpose(a[-l-1]))))
            all_delta_b[-l] += delta

            delta_prev = delta

    if np.mod(i, 1000) == 0:
        print('Epoch: %d - %f\r' % (i, C/20), end='')

    # Update Weights and Biases
    weights = weights - lr/4 * all_delta_w
    biases = biases - lr/4 * all_delta_b

    all_delta_w *= 0
    all_delta_b *= 0

In [ ]:
import matplotlib.pyplot as plt

def get_prediction(x):
    a = [x]
    z_inp = np.array(x)
    z = []
    for w, b in zip(weights, biases):
        z += [np.dot(z_inp, w) + b]
        a += [sigmoid(z[-1])]
        z_inp = a[-1]

    y = np.argmax(a[-1])

    return y

i = 200

num_row = 5
num_col = 5
fig, axes = plt.subplots(num_row, num_col, figsize=(1.5*num_col,2*num_row))
for i in range(25):
    idx = np.random.choice(len(X_test), size=1)
    img = np.squeeze(X_test[idx])
    img_R = np.reshape(img, 28*28)
    ax = axes[i//num_col, i%num_col]
    ax.axis('off')
    ax.imshow(img)
    ax.set_title('Label: %d' % (get_prediction(img_R)))
plt.tight_layout()
plt.show()



In [ ]:
y_pred = []

for x in X_test_R:
    x = x/255
    a = [x]
    z_inp = np.array(x)
    z = []
    for w, b in zip(weights, biases):
        z += [np.dot(z_inp, w) + b]
        a += [sigmoid(z[-1])]
        z_inp = a[-1]

    y_pred += [np.argmax(a[-1])]

In [ ]:
from sklearn.metrics import accuracy_score

score = accuracy_score(Y_test, np.array(y_pred))

print(score)



In [ ]:
accuracy_score(Y_test, np.array(y_pred))

In [ ]:
print(np.shape(weights[0]))

plt.figure(figsize=(10, 10))
plt.imshow(np.abs(np.reshape(np.mean(weights[0], axis=1), (28, 28))))
plt.show()