In [59]:
import numpy as np
# Define Sigmoid Function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

# Define Derivative of Sigmoid Function
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

X = [[0, 0], [0, 1], [1, 0], [1, 1]]
Y = [0, 1, 1, 1]

lr = 0.5
w0 = np.array([[0.3, 0.4], [0.1, 0.2], [0.1, 0.2]]).T
b0 = [1, 1, 1]
w1 = np.array([[0.5, 0.1, 0.2], [0.5, 0.1, 0.5], [0.25, 0.25, 0.1], [0.25, 0.25, 0.1]]).T
b1 = [1, 1, 1, 1]
w2 = [0.3, 0.4, 0.5, 0.3]
b2 = 1

x = [0, 0]
y = 0

for i in range(200000):
    del_w0 = 0
    del_b0 = 0
    del_w1 = 0
    del_b1 = 0
    del_w2 = 0
    del_b2 = 0
    C = 0
    for x, y in zip(X, Y):
        z0 = np.dot(x, w0) + b0
        a0 = sigmoid(z0)

        z1 = np.dot(a0, w1) + b1
        a1 = sigmoid(z1)

        z2 = np.dot(a1, w2) + b2
        a2 = sigmoid(z2)

        C += 0.5*(y - a2)**2

        delta = (a2 - y) * sigmoid_der(z2)
        del_w2 += np.dot(delta, np.transpose(a1))
        del_b2 += delta

        delta_1 = np.dot(np.transpose(w2), delta) * sigmoid_der(z1)

        print(np.shape(delta_1)
        print(np.shape(a0))

        del_w1 += np.outer(delta_1, np.transpose(a0))
        del_b1 += delta_1

        delta_0 = np.dot(w1, delta_1) * sigmoid_der(z0)

        del_w0 += np.outer(delta_0, np.transpose(x))
        del_b0 += delta_0
    
    if np.mod(i, 1000) == 0:
        print('Epoch: %d - %f\r' % (i, C/4), end='')

    w0 -= (lr/4) * np.transpose(del_w0)
    b0 -= (lr/4) * del_b0
    w1 -= (lr/4) * np.transpose(del_w1)
    b1 -= (lr/4) * del_b1
    w2 -= (lr/4) * del_w2
    b2 -= (lr/4) * del_b2

Epoch: 12000 - 0.000353Epoch: 13000 - 0.000281

KeyboardInterrupt: 

In [61]:
all_w = []
all_w += [w0]
all_w += [w1]
all_w += [w2]

print(np.shape(all_w))
print(all_w[0])
print(all_w[1])
print(all_w[2])
print(np.shape(all_w[2]))
print([w0,w1,w2])

for w in all_w:
    print(w)
    print(np.shape(w))

(3,)
[[ 3.97371835 -0.277124    1.05331731]
 [ 3.99440555 -0.15915012  1.12011585]]
[[ 2.95520796  4.63692813  3.41043873 -0.28105818]
 [-0.86428772 -1.16533835 -0.75156268  0.51289565]
 [ 0.21088619  0.73380511  0.25458186  0.0822635 ]]
[ 2.73832238  5.19033374  3.35557492 -1.80856932]
(4,)
[array([[ 3.97371835, -0.277124  ,  1.05331731],
       [ 3.99440555, -0.15915012,  1.12011585]]), array([[ 2.95520796,  4.63692813,  3.41043873, -0.28105818],
       [-0.86428772, -1.16533835, -0.75156268,  0.51289565],
       [ 0.21088619,  0.73380511,  0.25458186,  0.0822635 ]]), array([ 2.73832238,  5.19033374,  3.35557492, -1.80856932])]
[[ 3.97371835 -0.277124    1.05331731]
 [ 3.99440555 -0.15915012  1.12011585]]
(2, 3)
[[ 2.95520796  4.63692813  3.41043873 -0.28105818]
 [-0.86428772 -1.16533835 -0.75156268  0.51289565]
 [ 0.21088619  0.73380511  0.25458186  0.0822635 ]]
(3, 4)
[ 2.73832238  5.19033374  3.35557492 -1.80856932]
(4,)


In [44]:
x = [0, 0]

z0 = np.dot(x, w0) + b0
a0 = sigmoid(z0)

z1 = np.dot(a0, w1) + b1
a1 = sigmoid(z1)

z2 = np.dot(a1, w2) + b2
a2 = sigmoid(z2)

print(a2)

0.005165241652459693
